### ISSUE TITLE
Score Card Component

### ISSUE THREAD

**Issue by joseRFernandez** [team-awesome1/awesome_cards#15]
Tickets Needed -
- [x]  Figma Design of Score Card in isolation
- [x] Figma design of ScoreCard as expected on its relative View
- [ ] Data Flow Scheme
- [x] React Skeleton of ScoreCard Component
- [ ] Tests [ correct classes/CSS is passed, correct score props are passed, score is updated ]

**Comment by tmflower** [comment]
Hi everyone, I have preliminary drafts ready of what the scorecard could look like and would love to get some feedback if you have time to take a look. You'll find them on the same Figma board we've been using, just above Kit's original wireframes. I'm happy to make revisions based on any feedback you have. :)
[](https://www.figma.com/file/7sZy8bbclWAOzGdZUKVnsM/Wireframes?node-id=0%3A1)

**Comment by tmflower** [comment]
https://www.figma.com/file/7sZy8bbclWAOzGdZUKVnsM/Wireframes?node-id=0%3A1
