### ISSUE TITLE
Home Page Component

### ISSUE THREAD

**Issue by samuelhatcliff** [team-awesome1/awesome_cards#4]
Create homepage component to display background from figma design. All other components should be descendants of this component. 

- [x] create home page component 
- [x] return JSX containing all components we want (buttons and logo). //??
- [x] write tests to ensure that all child components are rendering
- [x] design homepage architecture 
- [x] apply background from figma
- [x] position all visible components on homepage
- [x] write css media queries to ensure that app is responsive to screen size and behaves nicely

Acceptance Criteria
  - default homepage rendered
  -  2 tests

**Comment by samuelhatcliff** [comment]
hey @tmflower did you have a question about the 2nd task? I see a "//??" afterwards. Definitely let me know if I can clarify or help with anything!

**Comment by joseRFernandez** [comment]
hey @samuelhatcliff - that was me. i was confused as to the general wording.  mainly what return 'jsx containing all components we want' meant.  are you able to clarify?
